print("Welcome to the slope of a line calculator!")
print("What is your y2?")
y2 = input()
print("What is your y1?")
y1 = input()
print("What is your x2?")
x2 = input()
print("What is your x1?")
x1 = input()
print("The slope of your line is " + str((float(y2)-float(y1))/((float(x2)-float(x1)))))
